### ISSUE TITLE
Question: What does the facebook patch do?

### ISSUE THREAD

**Issue by BigBellyKing** [NeonOrbit/MRVPatchManager#10]
I'm sorry for the stupid question but I'm just curious if the patched facebook app is any different to vanilla facebook app

**Comment by NeonOrbit** [comment]
It's just like the vanilla app. 
To install Facebook with a patched Messenger, the Facebook app has to be signed with the same signature. However, using a custom signature can cause issues with key features like login sharing, account center, and link opening. That's why patching is necessary to ensure it functions just like the vanilla Facebook app.
